Improvements and fixes
stackhpc/terraform-kayobe-multinode pull request #10
Opened 2022-11-24 10:09 UTC by jackhodgkiss

- Require VXLAN VNI is set for `deploy-openstack-config.yml` to prevent collisions with the default value
- Improve documentation with full commands
- Fix issue with `deploy-openstack.sh` would fail to run tempest
- Sleep to allow tempest to start on seed

Could benefit from pinning version of kayobe-config, kayobe and openstack-config here.

This has been tested three times.

2022-12-01 16:35 UTC, markgoddard requested changes

2022-12-01 16:35 UTC, markgoddard commented on ansible/fix-homedir-ownership.yml
> +      loop: "{{ admin_oc_ips | combine({'ansible-host': inventory_hostname}) | dict2items }}"
ansible_host is the address used to connect to the machine

2023-02-01 12:29 UTC, jackhodgkiss commented on templates/deploy-openstack.tpl
> +sleep 360
Comment has now been provided.

2023-02-02 10:57 UTC, markgoddard commented on ansible/deploy-openstack-config.yml
> +        fail_msg: "Please provide a VXLAN VNI. A unique value from 1 to 16777215."
Didn't you find that a very high number would lead to an invalid multicast IP?

2023-02-02 11:03 UTC, markgoddard approved these changes

2023-02-02 11:04 UTC, merged